all:
  children:
    control:
      hosts:
        control01:
          ansible_connection: local
    web:
      hosts:
        web01.admin:
          ansible_host: 127.0.0.1
    apache2:
      hosts:
        apache01.admin:
          ansible_host: 127.0.0.1
